name: "Notify Guard"
version: "1.0.15"
slug: "notify_guard"
description: "Reliable messaging service with queue and history (Retries & SQLite)"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
panel_icon: mdi:bell-ring
panel_title: Notify Guard
panel_admin: true
ingress: true
ingress_port: 8000
hassio_api: true
homeassistant_api: true
map:
  - addon_config:rw
